//Useful references
var CONST = chartSpace.Constants;

// Add a caption
chartSpace.HasChartSpaceTitle = true;
chartSpace.ChartSpaceTitle.Caption = "Generated by Log Parser 2.2";
chartSpace.ChartSpaceTitle.Font.Size = 6;
chartSpace.ChartSpaceTitle.Position = chartSpace.Constants.chTitlePositionBottom;

// Change the background color
chart.PlotArea.Interior.Color = chartSpace.Constants.chColorNone;

//Make the bars wide
chart.SeriesCollection(0).GapWidth = 10;
 
//Create a secondary Axis for the second series
if (chart.SeriesCollection.Count > 1) {
	var series2 = chart.SeriesCollection(1);
	series2.Ungroup(true);
	series2.GapWidth = 100;
	var axisRight = chart.Axes.Add(series2.Scalings(CONST.chDimValues));
	axisRight.Position = CONST.chAxisPositionRight;
}
